<?php

namespace AppBundle\Repository;

/**
 * Teister_MaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Teister_MaskRepository extends \Doctrine\ORM\EntityRepository
{
}
