<?php

namespace AppBundle\Repository;

/**
 * TeistermaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeistermaskRepository extends \Doctrine\ORM\EntityRepository
{
}
